---
- name: Check if Atuin is installed
  ansible.builtin.stat:
    path: "{{ homebrew_config.paths.bin }}/atuin"
  register: atuin_binary

- name: Check required environment variables
  ansible.builtin.set_fact:
    atuin_env_vars:
      username: "{{ lookup('env', 'ATUIN_USERNAME', default='') }}"
      password: "{{ lookup('env', 'ATUIN_PASSWORD', default='') }}"
      key: "{{ lookup('env', 'ATUIN_KEY', default='') }}"

- name: Verify Atuin credentials are available
  ansible.builtin.assert:
    that:
      - atuin_env_vars.username | length > 0
      - atuin_env_vars.password | length > 0
      - atuin_env_vars.key | length > 0
    fail_msg: "Missing required Atuin environment variables"
    success_msg: "All required Atuin credentials are available"
  when: atuin_binary.stat.exists
  ignore_errors: true
  register: credentials_check

- name: Login to Atuin
  ansible.builtin.command:
    cmd: atuin login -u "{{ atuin_env_vars.username }}" -p "{{ atuin_env_vars.password }}" -k "{{ atuin_env_vars.key }}"
  when:
    - atuin_binary.stat.exists
    - credentials_check is success
  register: login_result
  changed_when: login_result.rc == 0
  failed_when: false

- name: Sync Atuin history
  ansible.builtin.command: atuin sync
  when:
    - atuin_binary.stat.exists
    - credentials_check is success
    - login_result.rc == 0
  changed_when: false
