---
- name: Install development tools
  block:
    - name: Configure environment
      ansible.builtin.set_fact:
        node_version: "23"

    - name: Install curl
      ansible.builtin.apt:
        name: curl
        state: present
      become: true

    - name: Download NodeSource setup script
      ansible.builtin.get_url:
        url: "https://deb.nodesource.com/setup_{{ node_version }}.x"
        dest: /tmp/nodesource_setup.sh
        mode: '0755'
      when: not ansible_check_mode

    - name: Run NodeSource setup script
      ansible.builtin.command: bash /tmp/nodesource_setup.sh
      become: true
      changed_when: false
      when: not ansible_check_mode

    - name: Install Node.js
      ansible.builtin.apt:
        name: nodejs
        state: present
        update_cache: true
      become: true
      register: nodejs_install

    - name: Setup PNPM
      ansible.builtin.shell: |
        if ! command -v pnpm &> /dev/null; then
          npm install -g pnpm
          echo "changed"
        fi
      register: pnpm_install
      changed_when: pnpm_install.stdout is search("changed")

    - name: Install bun
      ansible.builtin.shell: |
        if ! command -v bun &> /dev/null; then
          npm install -g bun
          echo "changed"
        fi
      register: bun_install
      changed_when: bun_install.stdout is search("changed")

  rescue:
    - name: Debug installation failures
      ansible.builtin.debug:
        msg: |
          Installation failed:
          Node.js: {{ nodejs_install.failed | default(false) }}
          PNPM: {{ pnpm_install.failed | default(false) }}
          Bun: {{ bun_install.failed | default(false) }}
