---
- name: Create backup directory for existing dotfiles
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/dotfiles_backup_{{ ansible_date_time.epoch }}"
    state: directory
    mode: "0755"

- name: Check for existing dotfiles
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/{{ item }}"
  register: dotfile_stats
  with_items: "{{ symlink_dotfiles | default([]) }}"
  failed_when: false

- name: Backup existing dotfiles
  ansible.builtin.command: mv "{{ ansible_env.HOME }}/{{ item.item }}" "{{ ansible_env.HOME }}/dotfiles_backup_{{ ansible_date_time.epoch }}/"
  with_items: "{{ dotfile_stats.results | default([]) }}"
  when: item.stat.exists | default(false)
  register: backup_dotfiles
  changed_when: backup_dotfiles.rc == 0
  failed_when: backup_dotfiles.rc != 0 and "No such file or directory" not in backup_dotfiles.stderr

- name: Create symlinks for dotfiles
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/dotfiles/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    state: link
    force: true
  with_items: "{{ symlink_dotfiles | default([]) }}"
  failed_when: false

- name: Ensure .config directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    mode: "0755"

- name: Check for existing config directories
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.config/{{ item }}"
  register: config_stats
  with_items: "{{ config_dirs | default([]) }}"
  failed_when: false

- name: Backup existing config directories
  ansible.builtin.command: mv "{{ ansible_env.HOME }}/.config/{{ item.item }}" "{{ ansible_env.HOME }}/dotfiles_backup_{{ ansible_date_time.epoch }}/"
  with_items: "{{ config_stats.results | default([]) }}"
  when: item.stat.exists | default(false)
  register: backup_configs
  changed_when: backup_configs.rc == 0
  failed_when: backup_configs.rc != 0 and "No such file or directory" not in backup_configs.stderr

- name: Create symlinks for config directories
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/dotfiles/config/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/{{ item }}"
    state: link
    force: true
  with_items: "{{ config_dirs }}"
