---
- name: Configure Remote Development Environment
  hosts: all
  gather_facts: true
  vars_files:
    - vars/main.yml
  become: true
  remote_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
  tags: always

  pre_tasks:
    - name: Print progress information
      ansible.builtin.debug:
        msg: "Starting configuration of remote host {{ ansible_hostname }}"
      tags: always

    - name: Ensure required directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"
      loop:
        - "{{ ansible_env.HOME }}/dotfiles"
        - "{{ ansible_env.HOME }}/.config"

    - name: Synchronize dotfiles to remote host
      ansible.posix.synchronize:
        src: "{{ playbook_dir }}/../"
        dest: "{{ ansible_env.HOME }}/dotfiles/"
        delete: true
        rsync_opts:
          - "--exclude=.git"
      become: false

  roles:
    - role: system
      tags: ['system', 'packages']
    - role: artis3n.tailscale
      tags: ['tailscale']
      vars:
        tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}"
        tailscale_args: "--ssh"
      when: (lookup('env', 'TAILSCALE_KEY') is defined) and not (lookup('env', 'DOTFILES_TEST') is defined)
    - role: homebrew
      tags: ['homebrew']
    - role: dotfiles
      tags: ['dotfiles']
    - role: shell
      tags: ['shell']
    - role: tpm
      tags: ['tpm']
    - role: atuin
      tags: ['atuin']
    - role: dev
      tags: ['dev']

  post_tasks:
    - name: Print completion status
      ansible.builtin.debug:
        msg: "Configuration completed successfully on {{ ansible_hostname }}"
      tags: always
