---
- name: Configure Local Environment
  hosts: localhost
  gather_facts: true
  vars_files:
    - vars/main.yml
  tags: always

  pre_tasks:
    - name: Print progress information
      ansible.builtin.debug:
        msg: "Starting configuration of {{ ansible_hostname }}"
      tags: always

  roles:
    - role: system
      tags: ['system', 'packages']
    - role: artis3n.tailscale # https://github.com/artis3n/ansible-role-tailscale
      tags: ['tailscale']
      vars:
        tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}"
        tailscale_args: "--ssh"
      when: (lookup('env', 'TAILSCALE_KEY') is defined) and not (lookup('env', 'DOTFILES_TEST') is defined)
    - role: homebrew
      tags: ['homebrew']
    - role: dotfiles
      tags: ['dotfiles']
    - role: shell
      tags: ['shell']
    - role: tpm
      tags: ['tpm']

  post_tasks:
    - name: Print completion status
      ansible.builtin.debug:
        msg: "Configuration completed successfully on {{ ansible_hostname }}"
      tags: always
